project:
  type: website

website:
  title: "Deniz Zorlu"
  navbar:
    left:
      - text: Posts
        href: posts/

format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: false
  warning: false


