project:
  type: website

website:
  title: "Tinkerings"
  site-url: https://tinkerings.dev

resources:
  - static/moe.html
  - static/moe-preview.png
  - images/**

format:
  html:
    theme: darkly
    highlight-style: monokai
    code-copy: true
    code-line-numbers: true
    code-block-bg: "#0e1117"
    code-block-border-left: "#00d1b2"

execute:
  echo: false
  warning: false




