project:
  type: website

website:
  title: "Tinkerings"
  site-url: https://tinkerings.dev
  navbar:
    left:
      - text: Posts
        href: posts/

resources:
  - static/moe.html
  - static/moe-preview.png

format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: false
  warning: false


